[tool.black]
exclude = '''
/(
  | \.git
  | \.venv
  | \__pycache__
  | \docs/source/conf.py
  | \wsgi.py
  | \old
  | \build
  | \dist
)/
'''


[tool.pytest.ini_options]
minversion = "6.1"
addopts = '''
  -v
  -s
  --junitxml=ci_result/junit.xml
  --html=ci_result/report.html --self-contained-html  
  --cov app
  --cov-report html:ci_result/html-cov
  --cov-report xml:ci_result/cov.xml
'''
testpaths = [
  "tests",
]