"""update users table

Revision ID: 95d08c13ed58
Revises: e683dce975f4
Create Date: 2020-08-29 22:03:17.896369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95d08c13ed58"
down_revision = "e683dce975f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=16), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=16), nullable=False))
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
